---
## => Main File Collect All Ansible Roles

- import_playbook: plays/packages.yml
- import_playbook: plays/k8s.yml
- import_playbook: plays/aws.yml
- import_playbook: plays/ingress.yml
- import_playbook: plays/docker.yml
- import_playbook: plays/elk.yml
- import_playbook: plays/jenkins.yml
- import_playbook: plays/sonarqube.yml
- import_playbook: plays/prometheus.yml
- import_playbook: plays/resources.yml